version: 0.2

env:
  variables:
    IMAGE_NAME: Golden
    LAUNCH_TEMPLATE_NAME: version1
    ASG_NAME: ASG

phases:
  build:
    commands:
      - echo "==== Fetching latest AMI from Image Builder ===="

      - |
        AMI_ID=$(aws imagebuilder list-images \
          --owner Self \
          --query "imageVersionList[?name=='${IMAGE_NAME}'] | sort_by(@,&dateCreated)[-1].outputResources.amis[0].image" \
          --output text)

        if [ -z "$AMI_ID" ] || [ "$AMI_ID" = "None" ]; then
          echo "ERROR: No AMI found for Image Builder image: ${IMAGE_NAME}"
          exit 1
        fi

        echo "Latest AMI ID: $AMI_ID"

      - echo "==== Creating new Launch Template version ===="

      - |
        aws ec2 create-launch-template-version \
          --launch-template-name "$LAUNCH_TEMPLATE_NAME" \
          --source-version '$Latest' \
          --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"

      - echo "==== Setting new Launch Template version as default ===="

      - |
        aws ec2 modify-launch-template \
          --launch-template-name "$LAUNCH_TEMPLATE_NAME" \
          --default-version '$Latest'

      - echo "==== Starting ASG Instance Refresh ===="

      - |
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name "$ASG_NAME" \
          --preferences '{"MinHealthyPercentage":90,"InstanceWarmup":300}'

      - echo "==== Deployment completed successfully ===="
