version: 0.2
env:
  variables:
    IMAGE_NAME: Golden
    LAUNCH_TEMPLATE_NAME: version1
    ASG_NAME: ASG
    IMAGE_QUERY: 'imageVersionList[?name==`autobackedami`][-1].outputResources.amis[0].image'
phases:
  build:
    commands:
      - echo "Fetching latest AMI from Image Builder..."
      - AMI_ID=$(aws imagebuilder list-images --owner Self --query "$IMAGE_QUERY" --output text)
      - echo "Latest AMI $AMI_ID"
      - |
        aws ec2 create-launch-template-version \
          --launch-template-name "$LAUNCH_TEMPLATE_NAME" \
          --source-version '$Latest' \
          --launch-template-data '{"ImageId":"'"$AMI_ID"'"}'
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE_NAME" --default-version '$Latest'
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --preferences '{"MinHealthyPercentage":100,"InstanceWarmup":300}'
