version: 0.2
env:
  variables:
    IMAGE_NAME: Golden-Ami
    LAUNCH_TEMPLATE_NAME: Version1
    ASG_NAME: ASG
phases:
  build:
    commands:
      - echo "Fetching latest AMI from Image Builder..."
      - AMI_ID=$(aws imagebuilder list-images --owner Self --query "imageVersionList[?name=='Golden-Ami'][-1].outputResources.amis[0].image" --output text)
      - echo "Latest AMI $AMI_ID"
      - |
        if [ -z "$AMI_ID" ] || [ "$AMI_ID" = "None" ]; then
          echo "ERROR: No AMI found with name 'Golden-Ami'"
          echo "Listing all Image Builder images:"
          aws imagebuilder list-images --owner Self --query "imageVersionList[*].[name,outputResources.amis[0].image]" --output table
          exit 1
        fi
      - echo "Creating new launch template version..."
      - aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE_NAME" --source-version \$Latest --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"
      - echo "Setting new version as default..."
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE_NAME" --default-version \$Latest
      - echo "Starting instance refresh..."
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --preferences '{"MinHealthyPercentage":100,"InstanceWarmup":300}'
      - echo "Build completed successfully!"
