version: 0.2
env:
  variables:
    IMAGE_NAME: Golden-Ami
    LAUNCH_TEMPLATE_NAME: Version1
    ASG_NAME: ASG
phases:
  build:
    commands:
      - echo "Fetching latest Golden-Ami AMI from EC2..."
      - AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=Golden-Ami*" --query "Images | sort_by(@, &CreationDate)[-1].ImageId" --output text)
      - echo "Latest AMI $AMI_ID"
      - |
        if [ -z "$AMI_ID" ] || [ "$AMI_ID" = "None" ]; then
          echo "ERROR: No AMI found"
          echo "Listing all AMIs with Golden-Ami in name:"
          aws ec2 describe-images --owners self --filters "Name=name,Values=Golden-Ami*" --query "Images[*].[Name,ImageId,CreationDate]" --output table
          exit 1
        fi
      - echo "Creating new launch template version..."
      - aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE_NAME" --source-version \$Latest --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"
      - echo "Setting new version as default..."
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE_NAME" --default-version \$Latest
      - echo "Starting instance refresh..."
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --preferences '{"MinHealthyPercentage":100,"InstanceWarmup":300}'
      - echo "Build completed successfully!"
